### ISSUE TITLE
Log.log_exception() has a confusing interface

### ISSUE THREAD

**Issue by eric** [asenchi/scrolls#60]
I noticed the example shows using `Scrolls.log_exception(:at => "raise", e)` but ruby needs `{}` around the hash when it isn't the last argument: `Scrolls.log_exception({:at => "raise"}, e)`.

I had two questions:
1. Why is a hash required? Sometimes I've put everything I care about in the context already and just need to log the exception.
2. Why isn't the hash at the end so it doesn't need the `{}` around it?

**Comment by asenchi** [comment]
Turns out Ruby 2.x doesn't allow the "bare" hash anyways, so moving to the sane method shape with:

```
Scrolls.log_exception(e, {d: "d"})
```

This work has been completed in my major refactor: https://github.com/asenchi/scrolls/pull/71
