### ISSUE TITLE
Achieve true thread local context

### ISSUE THREAD

**Issue by rwdaigle** [asenchi/scrolls#61]
In an environment using a Fiber pool (such as an evented Rack app), setting a Scrolls context in a Rack middleware will not then be available to all scopes within that request.  This is because in Ruby 2.x `Thread.current[]=` behavior [does not actually set a thread-local variable](http://www.ruby-doc.org/core-2.1.1/Thread.html#method-i-5B-5D), but a Fiber-local one.

To achieve true thread locality you need to [use `thread_variable_get` (and `set`)](http://www.ruby-doc.org/core-2.1.1/Thread.html#method-i-thread_variable_get). I believe this is how context should be implemented?

``` ruby
module Scrolls
  module Log

    def context=(h)
      Thread.current.thread_variable_set(:scrolls_context, h || {})
    end

    def context
      Thread.current.thread_variable_get(:scrolls_context)
    end
  end
end
```

If so, let me know and I can submit a proper PR. One up front question would be your preference in Ruby version detection.

**Comment by asenchi** [comment]
I've fixed this behavior in my refactor: https://github.com/asenchi/scrolls/pull/71
