### ISSUE TITLE
Keys are not escaped

### ISSUE THREAD

**Issue by homakov** [asenchi/scrolls#67]
If someone uses something like Scrolls.log params[:data] then keys are coming from user input. These are not escaped and can create any log records. Is it an issue or not?

**Comment by asenchi** [comment]
Not sure this is a huge issue, but I think it makes sense to have the option, so I added it in my refactor in this commit: https://github.com/asenchi/scrolls/pull/71/commits/d4a250dff30eafac18901c22a3158ccfd44ed3ef

Basically allows you to do this:

```ruby
Scrolls.init(                                                                                                                                                 
  escape_keys: true
)
Scrolls.context(d: "d") do
  Scrolls.log("p/p" => "i")
  Scrolls.log("<p>data</p>" => "text")
end
```

Output:

```
d=d p&#x2F;p=i
d=d &lt;p&gt;data&lt;&#x2F;p&gt;=text
```
